name: deepgram_transcriber
description: "A Flutter app that uses Deepgram for real-time transcription."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  web_socket_channel: ^2.4.0
  permission_handler: ^10.3.0
  flutter_sound: ^9.2.13
  path_provider: ^2.1.1
  wakelock_plus: ^1.2.10
  url_launcher: ^6.2.5
  uni_links: ^0.5.1
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  
  assets:
    - assets/tenant_config.json
